### ISSUE TITLE
typescript error

### ISSUE THREAD

**Issue by bingtsingw** [zack37/referral-codes#9]
In `index.d.ts`
```
export = {
  CHARSETS,
  generate,
  charset,
};
```

The typescript compiler complains `The expression of an export assignment must be an identifier or qualified name in an ambient context.`

**Comment by zack37** [comment]
Hi @bingtsingw. Sorry for such a late reply. I had no idea anyone was using this library so I didn't bother checking issues for it. After seeing this issue, I've decided to rewrite the library with typescript to make sure my ham-fisted self typings were a non-issue. I've bumped the version to v2 now. Let me know if this fixes your issue or if you run into any other issues.

Thanks 😄
